# Generated by Django 3.1.7 on 2021-02-21 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField(blank=True)),
                ('created', models.DateField(default='2021-02-21')),
                ('due_date', models.DateField(default='2021-02-21')),
                ('is_complete', models.BooleanField(default=False)),
                ('category', models.ForeignKey(default='general', on_delete=django.db.models.deletion.CASCADE, to='rest.category')),
            ],
            options={
                'verbose_name': 'TODO',
                'verbose_name_plural': 'TODOS',
                'ordering': ['-created'],
            },
        ),
    ]
