# Generated by Django 3.1.7 on 2021-02-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20210221_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='useruid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='useruid',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
